
service: myserverlessproject

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    tableName: ${self:custom.tableName}
    bucketName: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource: '*'
  apiGateway:
    apiKeys:
      - name: MyFreeApiKey
        value: Lc9XtRmZ8OaJzKvS2q0F
      - name: MyPaidApiKey
        value: hY4sDpGnT3iXbM6oWfEj
  usagePlan:
    - name: my-free-plan
      description: My Free Plan
      free:
        quota:
          limit: 10000
          period: MONTH
        throttle:
          burstLimit: 500
          rateLimit: 200
    - name: my-paid-plan
      description: My Paid Plan
      paid:
        quota:
          limit: 50000
          period: MONTH
        throttle:
          burstLimit: 1000
          rateLimit: 500

functions:
  getUser:
    handler: lambdas/endpoints/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true
          private: true
  getPlayerScore:
    handler: lambdas/endpoints/getPlayerScore.handler
    events:
      - http:
          path: get-player-score/{ID}
          method: GET
          cors: true
  createPlayerScore:
    handler: lambdas/endpoints/createPlayerScore.handler
    events:
      - http:
          path: create-player-score/{ID}
          method: post
          cors: true
  createFile:
    handler: lambdas/endpoints/createFile.handler
    events:
      - http:
          path: create-file/{fileName}
          method: POST
          cors: true
  getFile:
    handler: lambdas/endpoints/getFile.handler
    events:
      - http:
          path: get-file/{fileName}
          method: GET
          cors: true
      
            
      

plugins:
  - serverless-s3-sync
  - serverless-webpack

package:
  individually: true

custom:
  tableName: player-points
  bucketName: jaimebucketjdewdiwjsiwjsjwisjwi
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: UploadData


resources:
  Resources:
    DemoBucke: 
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
